name: checks
run-name: Werewolf Backend Checks

on:
  pull_request:
    paths:
      - 'werewolf-backend/**'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup and execute Gradle 'check' task on backend
        uses: gradle/gradle-build-action@v2
        with:
          arguments: werewolf-backend:check
