name: checks
run-name: Werewolf Game Client Checks

on:
  pull_request:
    paths:
      - 'werewolf-game-client/**'

defaults:
  run:
    working-directory: ./werewolf-game-client/

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test
